import React from "react";
import { Payment, columns } from "./columns";
import { DataTable } from "./data-table";
const getData = async (): Promise<Payment[]> => {
  return [
    {
      id: "a1f7c9e0",
      amount: 120,
      status: "pending",
      email: "michael@gmail.com",
      username: "michael",
    },
    {
      id: "b29de1f3",
      amount: 240,
      status: "processing",
      email: "lisa@example.com",
      username: "lisa99",
    },
    {
      id: "c93bf712",
      amount: 310,
      status: "success",
      email: "mark@outlook.com",
      username: "mark_dev",
    },
    {
      id: "d8a1e3b2",
      amount: 90,
      status: "failed",
      email: "support@service.io",
      username: "support_bot",
    },
    {
      id: "e71af930",
      amount: 180,
      status: "pending",
      email: "hello@mail.com",
      username: "hello_user",
    },
    {
      id: "f22de7c1",
      amount: 500,
      status: "success",
      email: "billing@pay.com",
      username: "billing_master",
    },
    {
      id: "a73ec821",
      amount: 75,
      status: "processing",
      email: "test@site.dev",
      username: "tester",
    },
    {
      id: "b04f1ed2",
      amount: 210,
      status: "success",
      email: "orders@store.net",
      username: "orderman",
    },
    {
      id: "c56db913",
      amount: 330,
      status: "pending",
      email: "info@gmail.com",
      username: "infohub",
    },
    {
      id: "d38fa241",
      amount: 470,
      status: "success",
      email: "ceo@company.com",
      username: "ceo_admin",
    },
    {
      id: "e11cb9f4",
      amount: 255,
      status: "processing",
      email: "random@gmail.com",
      username: "randomguy",
    },
    {
      id: "f49ae0d8",
      amount: 130,
      status: "failed",
      email: "team@startup.io",
      username: "teamleader",
    },
    {
      id: "a82fd1c7",
      amount: 290,
      status: "success",
      email: "admin@web.dev",
      username: "admin_web",
    },
    {
      id: "b13ad4e0",
      amount: 420,
      status: "pending",
      email: "contact@mail.net",
      username: "contactme",
    },
    {
      id: "c90fb5a6",
      amount: 160,
      status: "processing",
      email: "alex@icloud.com",
      username: "alexcloud",
    },
    {
      id: "d54eb812",
      amount: 80,
      status: "pending",
      email: "support@brand.co",
      username: "brand_support",
    },
    {
      id: "e39da664",
      amount: 260,
      status: "failed",
      email: "hr@corporate.com",
      username: "hr_dept",
    },
    {
      id: "f78ac911",
      amount: 350,
      status: "success",
      email: "business@domain.com",
      username: "bizowner",
    },
    {
      id: "a25cf601",
      amount: 510,
      status: "processing",
      email: "sales@ecommerce.io",
      username: "salesforce",
    },
    {
      id: "b87db7a2",
      amount: 140,
      status: "pending",
      email: "user@mailbox.org",
      username: "user123",
    },
    {
      id: "c02ac41d",
      amount: 390,
      status: "success",
      email: "report@company.org",
      username: "reporter",
    },
    {
      id: "d44dc722",
      amount: 200,
      status: "processing",
      email: "news@webapp.com",
      username: "newsfeed",
    },
    {
      id: "e95ef103",
      amount: 305,
      status: "failed",
      email: "data@service.dev",
      username: "datanerd",
    },
    {
      id: "f62ea9d0",
      amount: 470,
      status: "pending",
      email: "ceo@mail.io",
      username: "bossman",
    },
    {
      id: "a07bd853",
      amount: 110,
      status: "success",
      email: "dev@company.io",
      username: "developer",
    },
    {
      id: "b41cc202",
      amount: 260,
      status: "processing",
      email: "marketing@brand.com",
      username: "marketer",
    },
    {
      id: "c15af734",
      amount: 600,
      status: "success",
      email: "founder@startup.com",
      username: "founder",
    },
    {
      id: "d30dc512",
      amount: 125,
      status: "failed",
      email: "info@mail.io",
      username: "info_user",
    },
    {
      id: "e88af430",
      amount: 80,
      status: "pending",
      email: "example@email.com",
      username: "exampleuser",
    },
    {
      id: "f17bd903",
      amount: 215,
      status: "success",
      email: "support@crm.io",
      username: "crm_support",
    },
    {
      id: "a56ee291",
      amount: 380,
      status: "processing",
      email: "billing@store.dev",
      username: "paymaster",
    },
    {
      id: "b64ae037",
      amount: 190,
      status: "failed",
      email: "team@work.io",
      username: "workteam",
    },
    {
      id: "c21bd612",
      amount: 330,
      status: "success",
      email: "sales@shop.com",
      username: "shopowner",
    },
    {
      id: "d72dc731",
      amount: 270,
      status: "pending",
      email: "person@mail.com",
      username: "person101",
    },
    {
      id: "e11bc874",
      amount: 450,
      status: "processing",
      email: "service@domain.net",
      username: "servicenow",
    },
    {
      id: "f63aa902",
      amount: 95,
      status: "success",
      email: "user@service.com",
      username: "useme",
    },
    {
      id: "a47db754",
      amount: 210,
      status: "failed",
      email: "payment@system.io",
      username: "paygate",
    },
    {
      id: "b90fe2a3",
      amount: 540,
      status: "pending",
      email: "orders@business.com",
      username: "orderflow",
    },
    {
      id: "c14db111",
      amount: 350,
      status: "success",
      email: "info@project.dev",
      username: "projector",
    },
    {
      id: "d11fa3e2",
      amount: 270,
      status: "processing",
      email: "notify@platform.com",
      username: "notifier",
    },
    {
      id: "e81bc4a0",
      amount: 150,
      status: "pending",
      email: "contact@site.io",
      username: "siteowner",
    },
    {
      id: "f05cb912",
      amount: 415,
      status: "success",
      email: "team@web.io",
      username: "webteam",
    },
  ];
};
async function page() {
  const data = await getData();
  return <DataTable columns={columns} data={data} />;
}

export default page;
