
import { ThemeProvider } from "../components/ui/theme/theme-provider"
import "./globals.css";
import AppSider from "./AppSider";
import Navbar from "./Navbar";
import { SidebarProvider, SidebarTrigger } from "../components/ui/sidebar.jsx";
import { TooltipProvider } from "../components/ui/tooltip.jsx";
import { cookies } from "next/headers";
// import { AppSidebar } from "@/components/app-sidebar"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <SidebarProvider defaultOpen={defaultOpen}>
              <div className="flex min-h-screen w-full" suppressHydrationWarning>
                <AppSider />
                <main className="w-full">
                  <Navbar />
                  <div className="px-4">
                    {children}
                  </div>
                </main>
              </div>
            </SidebarProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
